name: Continuous Delivery (CD)

on:
  push:
    branches: ["master"]

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout dépot
        uses: actions/checkout@v3

      - name: stop containers
        run: docker compose down -v

      - name: Pull new images
        run: docker compose pull || true

      - name: Start Docker services
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.DB_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          GATEWAY_SECRET: ${{ secrets.GATEWAY_SECRET }}
          SPRING_MAIL_USERNAME: ${{ secrets.SMTP_USER }}
          SPRING_MAIL_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: docker compose up -d --build